plugins { id 'com.android.application' }

android {
    namespace 'com.ilker.microsoftreport'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ilker.microsoftreport'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
        buildConfigField 'String', 'CLIENT_ID', '"' + (System.getenv('PARTNER_CENTER_CLIENT_ID') ?: '') + '"'
        buildConfigField 'String', 'TENANT_ID', '"' + (System.getenv('PARTNER_CENTER_TENANT_ID') ?: '') + '"'
    }

    buildFeatures { buildConfig true }
}
