plugins {
    id 'com.android.application'
}

android {
    namespace 'com.spg.storesales'
    compileSdk 35

    defaultConfig {
        applicationId 'com.spg.storesales'
        minSdk 23
        targetSdk 34
        versionCode 7
        versionName '2.4'
    }

    buildTypes {
        release { minifyEnabled false }
    }
}
