package com.ilker.microsoftreport;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;
public final class MicrosoftApi{
 public static final ZoneId REPORT_ZONE=ZoneId.of("Europe/Istanbul");private static final String DEV_CENTER="https://manage.devcenter.microsoft.com",RESOURCE=DEV_CENTER;private static final DateTimeFormatter API_DATE=DateTimeFormatter.ofPattern("M/d/yyyy",Locale.US);private final EnvConfig config;private String accessToken;private long accessExpiresAt;public MicrosoftApi(EnvConfig c){config=c;}public int validate()throws Exception{token();return fetchApplications().size();}
 public Models.Dashboard fetchToday()throws Exception{String t=token();Map<String,String>apps=fetchApplications();LocalDate today=LocalDate.now(REPORT_ZONE);List<Models.AppSale>sales=new ArrayList<>();String freshest="";for(Map.Entry<String,String>a:apps.entrySet()){AcquisitionResult r;try{r=fetchAppAcquisitions(t,a.getKey(),a.getValue(),today);}catch(HttpException e){if(e.status==404||e.status==409)continue;throw e;}if(!r.dataFreshness.isEmpty()&&r.dataFreshness.compareTo(freshest)>0)freshest=r.dataFreshness;if(r.sale!=null&&r.sale.quantity>0)sales.add(r.sale);}return new Models.Dashboard(today.toString(),Instant.now().toString(),freshest,sales);}
 private synchronized String token()throws Exception{long now=System.currentTimeMillis();if(accessToken!=null&&now+120000L<accessExpiresAt)return accessToken;String ep="https://login.microsoftonline.com/"+encPath(config.tenantId)+"/oauth2/token";String body="grant_type=client_credentials&client_id="+enc(config.clientId)+"&client_secret="+enc(config.clientSecret)+"&resource="+enc(RESOURCE);JSONObject o=new JSONObject(request("POST",ep,null,"application/x-www-form-urlencoded",body.getBytes(StandardCharsets.UTF_8)));String t=o.optString("access_token","");if(t.isEmpty())throw new IllegalStateException(cleanError(o));accessToken=t;accessExpiresAt=now+Math.max(300L,o.optLong("expires_in",3600L))*1000L;return t;}
 private Map<String,String> fetchApplications()throws Exception{String t=token();LinkedHashMap<String,String>r=new LinkedHashMap<>();String u=DEV_CENTER+"/v1.0/my/applications?top=100";int g=0;while(u!=null&&g++<100){JSONObject root=new JSONObject(request("GET",u,t,null,null));JSONArray a=root.optJSONArray("value");if(a==null)a=root.optJSONArray("Value");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);String id=x.optString("id",x.optString("applicationId","")).trim();String n=x.optString("primaryName",x.optString("applicationName","")).trim();if(!id.isEmpty())r.put(id,n.isEmpty()?id:n);}String next=root.optString("@nextLink","").trim();if(next.isEmpty())u=null;else if(next.startsWith("http"))u=next;else u=DEV_CENTER+"/v1.0/my/"+next.replaceFirst("^/+","");}return r;}
 private AcquisitionResult fetchAppAcquisitions(String t,String id,String primary,LocalDate date)throws Exception{String d=API_DATE.format(date);String u=DEV_CENTER+"/v1.0/my/analytics/appacquisitions?applicationId="+enc(id)+"&startDate="+enc(d)+"&endDate="+enc(d)+"&aggregationLevel=day&groupby="+enc("date,applicationName,acquisitionType")+"&top=10000&skip=0";JSONObject root=new JSONObject(request("GET",u,t,null,null));JSONArray a=root.optJSONArray("Value");if(a==null)a=root.optJSONArray("value");int q=0;double gross=0,tax=0;String apiName="";if(a!=null)for(int i=0;i<a.length();i++){JSONObject row=a.getJSONObject(i);String type=row.optString("acquisitionType","").trim();double rg=finite(row.optDouble("purchasePriceUSDAmount",0)),rt=finite(row.optDouble("purchaseTaxUSDAmount",0));int rq=Math.max(0,row.optInt("acquisitionQuantity",0));boolean sold=type.equalsIgnoreCase("Paid")||type.equalsIgnoreCase("Pre Order");if(!sold&&rg<=0)continue;if(type.equalsIgnoreCase("Iap")||type.equalsIgnoreCase("Subscription Iap"))continue;q+=rq;gross+=rg;tax+=rt;String n=row.optString("applicationName","").trim();if(!n.isEmpty())apiName=n;}String n=!apiName.isEmpty()?apiName:primary;if(n==null||n.trim().isEmpty())n=id;Models.AppSale s=q>0?new Models.AppSale(id,n.trim(),q,gross,tax):null;return new AcquisitionResult(s,root.optString("DataFreshnessTimestamp",root.optString("dataFreshnessTimestamp","")));}
 private static double finite(double v){return Double.isNaN(v)||Double.isInfinite(v)?0:v;}
 private static String request(String method,String urlText,String bearer,String ct,byte[]body)throws Exception{URL u=new URL(urlText);requireMicrosoft(u);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(20000);c.setReadTimeout(30000);c.setInstanceFollowRedirects(false);c.setRequestMethod(method);c.setRequestProperty("Accept","application/json");c.setRequestProperty("User-Agent","MicrosoftStoreAnalytics-Android/3.0");if(bearer!=null&&!bearer.isEmpty())c.setRequestProperty("Authorization","Bearer "+bearer);if(ct!=null)c.setRequestProperty("Content-Type",ct);if(body!=null){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body);}}int code=c.getResponseCode();if(code>=300&&code<400){String loc=c.getHeaderField("Location");c.disconnect();if(loc==null)throw new HttpException(code,"Microsoft yönlendirmesi boş");URL r=new URL(loc);requireMicrosoft(r);return request(method,r.toString(),bearer,ct,body);}InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String text=read(in);c.disconnect();if(code<200||code>=300)throw new HttpException(code,"HTTP "+code+" "+concise(text));return text;}
 private static void requireMicrosoft(URL u){if(!"https".equalsIgnoreCase(u.getProtocol()))throw new SecurityException("Yalnızca HTTPS desteklenir");String h=u.getHost().toLowerCase(Locale.ROOT);boolean ok=h.equals("login.microsoftonline.com")||h.equals("manage.devcenter.microsoft.com")||h.endsWith(".microsoft.com")||h.endsWith(".microsoftonline.com");if(!ok)throw new SecurityException("Microsoft dışı adres engellendi: "+h);}
 private static String read(InputStream in)throws Exception{if(in==null)return"";try(InputStream i=in;ByteArrayOutputStream o=new ByteArrayOutputStream()){byte[]b=new byte[8192];for(int n;(n=i.read(b))>=0;)o.write(b,0,n);return o.toString(StandardCharsets.UTF_8.name());}}
 private static String cleanError(JSONObject o){String d=o.optString("error_description","").trim();if(!d.isEmpty())return d.replaceAll("[\\r\\n]+"," ");String e=o.optString("error","Microsoft token alınamadı");return e.isEmpty()?"Microsoft token alınamadı":e;}
 private static String concise(String s){if(s==null)return"";String x=s.replaceAll("[\\r\\n\\t]+"," ").replaceAll("\\s{2,}"," ").trim();return x.length()>300?x.substring(0,300):x;}
 private static String enc(String s)throws Exception{return URLEncoder.encode(s,StandardCharsets.UTF_8.name());}private static String encPath(String s)throws Exception{String x=enc(s).replace("+","%20");if(x.contains("%2F")||x.contains("%5C"))throw new IllegalArgumentException("Tenant ID geçersiz");return x;}
 private static final class AcquisitionResult{final Models.AppSale sale;final String dataFreshness;AcquisitionResult(Models.AppSale s,String f){sale=s;dataFreshness=f==null?"":f;}}
 public static final class HttpException extends Exception{public final int status;HttpException(int s,String m){super(m);status=s;}}
}
