package com.ilker.microsoftreport;
import android.app.*;import android.content.*;import android.os.IBinder;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;
public final class PollService extends Service{
 public static final String ACTION_STATUS="com.ilker.microsoftreport.STATUS",ACTION_POLL_NOW="com.ilker.microsoftreport.POLL_NOW",EXTRA_STATUS="status",EXTRA_ERROR="error";private static final String CHANNEL_MONITOR="store_monitor_v3",CHANNEL_SALES="store_sales_v3";private static final int MONITOR_ID=3001;private static final long INTERVAL_SECONDS=120L;private ScheduledExecutorService scheduler;private final AtomicBoolean polling=new AtomicBoolean(false);
 @Override public void onCreate(){super.onCreate();createChannels();startForeground(MONITOR_ID,monitorNotification("İzleme aktif • 2 dakikada bir kontrol"));scheduler=Executors.newSingleThreadScheduledExecutor();scheduler.scheduleWithFixedDelay(this::pollSafely,0L,INTERVAL_SECONDS,TimeUnit.SECONDS);}
 @Override public int onStartCommand(Intent i,int f,int id){if(i!=null&&ACTION_POLL_NOW.equals(i.getAction())&&scheduler!=null)scheduler.execute(this::pollSafely);return START_STICKY;}
 private void pollSafely(){if(!polling.compareAndSet(false,true))return;try{AuthStore a=new AuthStore(this);if(!a.hasConfig()){broadcast("ENV yapılandırması bekleniyor",false);stopSelf();return;}updateMonitor("Microsoft Store kontrol ediliyor");Models.Dashboard d=new MicrosoftApi(a.load()).fetchToday();StateStore s=new StateStore(this);List<StateStore.SaleChange>changes=s.detectChanges(d);s.saveDashboard(d);for(StateStore.SaleChange c:changes)notifySale(c);String when=DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss",Locale.forLanguageTag("tr-TR")).withZone(ZoneId.of("Europe/Istanbul")).format(Instant.now());updateMonitor("Son kontrol: "+when+" TR");broadcast("Kontrol tamamlandı",false);}catch(Throwable e){String m=concise(e.getMessage());updateMonitor("Kontrol hatası");broadcast(m.isEmpty()?"Kontrol tamamlanamadı":m,true);}finally{polling.set(false);}}
 private void notifySale(StateStore.SaleChange c){Intent l=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent p=PendingIntent.getActivity(this,c.sale.appId.hashCode(),l,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);String body=c.sale.quantity+" adet • Net "+String.format(Locale.US,"$%,.2f",c.sale.netUsd());Notification n=new Notification.Builder(this,CHANNEL_SALES).setSmallIcon(R.drawable.ic_stat_analytics).setContentTitle(c.sale.appName).setContentText(body).setContentIntent(p).setAutoCancel(true).setCategory(Notification.CATEGORY_STATUS).build();((NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE)).notify(10000+Math.abs(c.sale.appId.hashCode()%10000),n);}
 private Notification monitorNotification(String text){PendingIntent p=PendingIntent.getActivity(this,1,new Intent(this,MainActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);return new Notification.Builder(this,CHANNEL_MONITOR).setSmallIcon(R.drawable.ic_stat_analytics).setContentTitle("Microsoft Store Analytics").setContentText(text).setOngoing(true).setOnlyAlertOnce(true).setContentIntent(p).setCategory(Notification.CATEGORY_SERVICE).build();}
 private void updateMonitor(String t){((NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE)).notify(MONITOR_ID,monitorNotification(t));}
 private void createChannels(){NotificationManager n=(NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);NotificationChannel m=new NotificationChannel(CHANNEL_MONITOR,"Store izleme servisi",NotificationManager.IMPORTANCE_LOW);m.setDescription("İki dakikalık arka plan kontrolünün Android foreground service bildirimi");n.createNotificationChannel(m);NotificationChannel s=new NotificationChannel(CHANNEL_SALES,"Yeni Store satışları",NotificationManager.IMPORTANCE_HIGH);s.setDescription("Yeni Microsoft Store satışı algılandığında bildirim");n.createNotificationChannel(s);}
 private void broadcast(String s,boolean e){Intent i=new Intent(ACTION_STATUS).setPackage(getPackageName());i.putExtra(EXTRA_STATUS,s);i.putExtra(EXTRA_ERROR,e);sendBroadcast(i);}private static String concise(String s){if(s==null)return"";String x=s.replaceAll("[\\r\\n\\t]+"," ").replaceAll("\\s{2,}"," ").trim();return x.length()>240?x.substring(0,240):x;}
 public static void ensureRunning(Context c){if(!new AuthStore(c).hasConfig())return;c.startForegroundService(new Intent(c,PollService.class));}public static void requestImmediate(Context c){if(!new AuthStore(c).hasConfig())return;c.startForegroundService(new Intent(c,PollService.class).setAction(ACTION_POLL_NOW));}@Override public void onDestroy(){if(scheduler!=null)scheduler.shutdownNow();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
